### ISSUE TITLE
Cancel upload causes error

### ISSUE THREAD

**Issue by megaomniglobalcorp** [uploadcare/ngx-uploadcare-widget#30] opened 2019-03-01 15:46 UTC
When I cancel an upload before it has finished I get a JS error. In chrome the message reads "ERROR TypeError: Cannot read property 'promise' of null", in Firefox the message reads "ERROR TypeError: "selectionPromise is null". The widget still continues to work but related call backs (on-change, on-progress...) are no longer called.

I have used a fresh NG project to test using the latest version of the widget.

**Comment by ZNick1982** [comment] 2019-03-01 18:30
Hello.
Thanks for your report.
I will take a look and reply to you shortly.

Kind regards,
Nikolay Zherdev.

**Comment by ZNick1982** [comment] 2019-03-05 11:20
Hello Craig.

The issue is fixed on: https://github.com/uploadcare/ngx-uploadcare-widget/pull/31
Thanks for your reporting.

Kind regards,
Nikolay Zherdev.

**Closed** 2020-04-15 14:05 UTC
